### ISSUE TITLE
Non-registered user can't edit their ad, no matter admin approved

### ISSUE THREAD

**Issue by svszombie** [osclass/osclass-plugins#127]
Non-registered user posts an item and both admin and non-registered user get email about it but the non-registered user can't edit their item. When non-registered user clicks on the {EDIT_LINK}, they see everything except the item fields to be edited and submit button. Footer is not included on edit page, either. I have checked the item-edit.php in the template folder and it (the footer) was included but not displayed on edit page.

**Comment by conejoninja** [comment]
Hi svszombie, did you modify the theme somehow?
which version of Osclass are you using?

Thanks

**Comment by svszombie** [comment]
Yes. The theme is a bit modified. I use modern theme and the mod consists of the fact that the address field is url without http://, not as actual street address. I have modified the language files for that, too. I use osclass 3.0, i think. That is what i see on bottom right when i login at back end.

I have also tried to replace the item-edit.php with it's original but same thing happens.

EDIT: I have just made a fresh install and it works there, so the problem must be within my theme. Will be looking for it.

**Comment by conejoninja** [comment]
I'm afraid I can not help you anymore if you don't tell me more information.

Since the bottom of the page is not shown. I will tell you to check every place where you have something like "echo someFunction()", probably the function is outputing and error and echo don't know how to write it. Of course, the problem should be located AFTER the blank start.

Thanks

**Comment by svszombie** [comment]
I have found it. I forgot to remove a function about payment on edit page. Sorry for that.
